version: "3.8"

services:
  pg:
    image: postgres:16
    container_name: pg
    hostname: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "postgres"
